### ISSUE TITLE
请问您有没有出现使用WGAN之后效果不如DCGAN的情况呢？

### ISSUE THREAD

**Issue by 848475885** [MashiMaroLjc/learn-GAN#1]
在将DCGAN模型改成WGAN之后发现效果出现了下降，从直观上看生成图片的效果不如同样结构的DCGAN

**Comment by MashiMaroLjc** [comment]
有，WGAN的损失有一段先上升后下降的时间，可能等网络完全收敛后的结果再对比会比较好
